### ISSUE TITLE
Consuming data problems

### ISSUE THREAD

**Issue by asnir** [confluentinc/examples#15]
#14 
Problems consuming data will using [SimpleConsumerExample](https://github.com/confluentinc/examples/blob/master/kafka-clients/consumer/src/main/java/io/confluent/examples/consumer/SimpleConsumerExample.java)
params:100000 page_visits 0 localhost 9092

> Oops:java.lang.IllegalArgumentException
java.lang.IllegalArgumentException
	at java.nio.Buffer.limit(Buffer.java:275)
	at kafka.api.FetchResponsePartitionData$.readFrom(FetchResponse.scala:37)
	at kafka.api.TopicData$$anonfun$1.apply(FetchResponse.scala:99)
	at kafka.api.TopicData$$anonfun$1.apply(FetchResponse.scala:97)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:245)
	at scala.collection.immutable.Range.foreach(Range.scala:166)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:245)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at kafka.api.TopicData$.readFrom(FetchResponse.scala:97)
	at kafka.api.FetchResponse$$anonfun$4.apply(FetchResponse.scala:169)
	at kafka.api.FetchResponse$$anonfun$4.apply(FetchResponse.scala:168)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
	at scala.collection.immutable.Range.foreach(Range.scala:166)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at kafka.api.FetchResponse$.readFrom(FetchResponse.scala:168)
	at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:135)
	at kafka.javaapi.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:47)
	at io.confluent.examples.consumer.SimpleConsumerExample.run(SimpleConsumerExample.java:149)
	at io.confluent.examples.consumer.SimpleConsumerExample.main(SimpleConsumerExample.java:218)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

I have tried to use [this one](https://github.com/confluentinc/examples/blob/master/kafka-clients/consumer/src/main/java/io/confluent/examples/consumer/ConsumerGroupExample.java), but it doesn't print anything... Am i missing something?
io.confluent.examples.consumer.ConsumerGroupExample

This following code doesn't consume the data.
```java

package io.confluent.examples.consumer;


import org.apache.avro.generic.GenericRecord;
import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.clients.producer.ProducerConfig;

import java.util.Arrays;
import java.util.Properties;

public class SimpleAvroConsumer {

    public static void main(String[] args) {
        Properties props = new Properties();
        props.put("bootstrap.servers", Consts.BROKER_LIST);
        props.put("group.id", "test12");
        props.put("enable.auto.commit", "true");
        props.put("auto.commit.interval.ms", "1000");
        props.put("session.timeout.ms", "30000");
        props.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG,
                io.confluent.kafka.serializers.KafkaAvroDeserializer.class);
        props.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG,
                io.confluent.kafka.serializers.KafkaAvroDeserializer.class);
        props.put("auto.offset.reset", "earliest");
        props.put("schema.registry.url", "http://localhost:8081");

        KafkaConsumer<String, GenericRecord> consumer = new KafkaConsumer<>(props);


        consumer.subscribe(Arrays.asList("page_visits"));
        while (true) {
            ConsumerRecords<String, GenericRecord> records = consumer.poll(1);
            for (ConsumerRecord<String, GenericRecord> record : records)
                System.out.printf("offset = %d, key = %s, value = %s \n", record.offset(), record.key(), record.value());
        }
    }
}
```

I have tried to consume the data using the rest API & it works just fine.

p.s. the doc [here](http://docs.confluent.io/2.0.1/schema-registry/docs/serializer-formatter.html#serializer-and-formatter) seems to be broken.

**Comment by miguno** [comment]
> p.s. the doc here seems to be broken.

Do you have more details about what is broken?  Also, I'd suggest to follow-up on this problem by creating a GH issue at https://github.com/confluentinc/schema-registry/issues, which is the repository where the docs above are maintained (otherwise your feedback might get lost here in the examples repo).

**Comment by asnir** [comment]
For example review this code.

```
import org.apache.avro.Schema;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.GenericRecord;
import org.apache.kafka.clients.producer.KafkaProducer;
import org.apache.kafka.clients.producer.ProducerConfig;
import org.apache.kafka.clients.producer.ProducerRecord;
import java.util.Properties;

Properties props = new Properties();
props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, "localhost:9092");
props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG,
          io.confluent.kafka.serializers.KafkaAvroSerializer.class);
props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG,
          io.confluent.kafka.serializers.KafkaAvroSerializer.class);
props.put("schema.registry.url", "http://localhost:8081");
KafkaProducer producer = new KafkaProducer(props);

String key = "key1";
String userSchema = "{\"type\":\"record\"," +
                    "\"name\":\"myrecord\"," +
                    "\"fields\":[{\"name\":\"f1\",\"type\":\"string\"}]}";
Schema.Parser parser = new Schema.Parser();
Schema schema = parser.parse(userSchema);
GenericRecord avroRecord = new GenericData.Record(schema);
avroRecord.put("f1", "value1");

record = new ProducerRecord<Object, Object>("topic1", key, avroRecord);
try {
  producer.send(record);
} catch(SerializationException e) {
  // may need to do something with it
}
```

**Comment by ewencp** [comment]
@asnir Which versions of broker and clients are you using? This looks like a type of error that can occur when they are mismatched. You generally need the client to be a version less than or equal to the broker version.

**Comment by asnir** [comment]
Thanks @ewencp , I will check it.
- The client support the latest version (0.9). 
- The images seems to work with confluent version 1.0 -> kafka broker 0.8.2

I hope that it will solve more problems like unreleased connections.
