### ISSUE TITLE
kafka client demo

### ISSUE THREAD

**Issue by ywqyunshan** [confluentinc/examples#150]
Exception in thread "main" java.lang.NoClassDefFoundError: io/confluent/common/config/ConfigException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:662)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:418)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:56)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:63)
	at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:338)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:188)
	at com.btzh.kafka.producer.MyProducer.init(MyProducer.java:53)
	at com.btzh.Main.start(Main.java:28)
	at com.btzh.Main.main(Main.java:55)

**Comment by miguno** [comment]
Without further information from your side we can't really help you to identify or fix the problem @ywqyunshan.

Notably:

* What was the command you ran that led to this error?
* What operating system are you using?

**Comment by ywqyunshan** [comment]
sorry，I has deploy confluentin （version is 3.1.2 ） in sever，test by kafka avro producer commond is good，but i write data   user java api in client ，above excepiton. @miguno

**Comment by ywqyunshan** [comment]
he problem has solved, missing the following dependency package
kafka-schema-registry-client.jar,common-config.jar,common-utils.jar,jackson-core.jar,jackson-databind.jar,jackson-databind.jar

**Comment by himanshusehgal** [comment]
Can you please tell me which maven dependency to use to get rid of this exception.
Thanks!
