### ISSUE TITLE
Caused by: java.lang.NoClassDefFoundError: org/codehaus/jackson/node/TextNode error

### ISSUE THREAD

**Issue by sunnypatel2141** [confluentinc/examples#151]
Hello,

I have followed the instructions on this page https://github.com/confluentinc/examples/tree/3.3.0-post/kafka-clients for producing 10 data records but I'm getting an error. 

I have cloned the repository and followed the three steps:

```
cd producer
mvn clean package
mvn exec:java -Dexec.mainClass="io.confluent.examples.producer.ProducerExample" \
  -Dexec.args="10 http://localhost:8081"
```

When I run the program, I get the following error:

```
Caused by: java.lang.NoClassDefFoundError: org/codehaus/jackson/node/TextNode
	at org.apache.avro.Schema$Parser.parse(Schema.java:1020)
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerDe.createPrimitiveSchema(AbstractKafkaAvroSerDe.java:60)
	at io.confluent.kafka.serializers.AbstractKafkaAvroSerDe.<clinit>(AbstractKafkaAvroSerDe.java:48)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:706)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:460)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:453)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:62)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:75)
	at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:360)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:287)
	at io.confluent.examples.producer.ProducerExample.main(ProducerExample.java:53)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.codehaus.jackson.node.TextNode
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more`
```

For some reason the jackson-core-asl jar is not being recognized. Can this be fixed with pom.xml? 

I'm using Mac if that helps.

**Comment by sunnypatel2141** [comment]
Fixed the problem by switching from Maven project to Java Project and configuring build path by adding the same dependencies (jars) from Maven Repository. I figure pom.xml in Maven project was adding a corrupt jar, or a jar with incorrect version (I don't know how) which caused the exception.
