### ISSUE TITLE
Problems with specific-avro-producer

### ISSUE THREAD

**Issue by asnir** [confluentinc/examples#17]
I am trying the [specific-avro-producer tutorial](https://github.com/confluentinc/examples/tree/master/kafka-clients/specific-avro-producer) and i am getting the following error.... any idea?

```
confluent@32e5dd06beda:/$ /usr/bin/kafka-avro-console-consumer --zookeeper zookeeper:2181 --topic clicks --from-beginning
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/share/java/confluent-common/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/java/schema-registry/slf4j-log4j12-1.7.6.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
[2016-03-17 07:29:42,369] ERROR Error processing message, stopping consumer:  (kafka.tools.ConsoleConsumer$:103)
org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 4
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:997)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:933)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:851)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1301)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        at io.confluent.kafka.schemaregistry.client.rest.utils.RestUtils.httpRequest(RestUtils.java:134)
        at io.confluent.kafka.schemaregistry.client.rest.utils.RestUtils.getId(RestUtils.java:228)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaByIdFromRegistry(CachedSchemaRegistryClient.java:56)
        at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getByID(CachedSchemaRegistryClient.java:100)
        at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:49)
        at io.confluent.kafka.formatter.AvroMessageFormatter.writeTo(AvroMessageFormatter.java:117)
        at io.confluent.kafka.formatter.AvroMessageFormatter.writeTo(AvroMessageFormatter.java:109)
        at kafka.tools.ConsoleConsumer$$anonfun$main$1.apply(ConsoleConsumer.scala:168)
        at kafka.tools.ConsoleConsumer$$anonfun$main$1.apply(ConsoleConsumer.scala:166)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at kafka.utils.IteratorTemplate.foreach(IteratorTemplate.scala:32)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at kafka.consumer.KafkaStream.foreach(KafkaStream.scala:25)
        at kafka.tools.ConsoleConsumer$.main(ConsoleConsumer.scala:166)
        at kafka.tools.ConsoleConsumer.main(ConsoleConsumer.scala)
[2016-03-17 07:29:42,369] ERROR Error processing message, stopping consumer:  (kafka.tools.ConsoleConsumer$:103)

```

p.s. The Kafka log (`docker logs kafka`) contains the following error:

```
[2016-03-16 16:05:07,491] ERROR Closing socket for /<MY_IP> because of error (kafka.network.Processor)
org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'topics': java.nio.BufferUnderflowException
        at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:66)
        at org.apache.kafka.common.requests.JoinGroupRequest.parse(JoinGroupRequest.java:85)
        at kafka.api.JoinGroupRequestAndHeader$.readFrom(JoinGroupRequestAndHeader.scala:29)
        at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
        at kafka.api.RequestKeys$$anonfun$12.apply(RequestKeys.scala:50)
        at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:50)
        at kafka.network.Processor.read(SocketServer.scala:450)
        at kafka.network.Processor.run(SocketServer.scala:340)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ewencp** [comment]
It looks like you don't have the schema registry running on `http://localhost:8081` since the connection is being refused, but clearly the data was written and assigned a schema since it's trying to look up schema ID 4. Given that you mentioned docker, my guess would be that the default URL used by `kafka-avro-console-consumer` isn't right for you -- you'd need to override it with `--property schema.registry.url=http://<schema-registry-host>:8081`

**Comment by asnir** [comment]
`/usr/bin/kafka-avro-console-consumer --zookeeper zookeeper:2181 schema.registry.url="http://schema-registry:8081" --topic clicks --from-beginning`
