### ISSUE TITLE
Failed to log into your Metadata Server

### ISSUE THREAD

**Issue by vschandra** [confluentinc/examples#233]
Hi 

I am getting following message when I ran examples-5.3.0-post/security/rbac/scripts/enable-rbac-broker.sh. 

When I logon to MDS from the console I am getting following message: http://localhost:8090
{"status_code":404,"message":"HTTP 404 Not Found","type":"CLIENT_ERROR"}. as user user mds/mds1. 

Waited till all the processing complete and restarted afterwards but I am still seeing the same error messages. Had my CONFLUENT_HOME and PATH set properly, expect binary exist in the path as well. 

Is there any thing that I am doing wrong that triggers this behaviour. This is on macOS

**Comment by vschandra** [comment]
MDS Logs showing following: 

==> metadata-service.log <==
[2019-08-17 14:01:04,399] DEBUG Invalid JWT (io.confluent.common.security.jetty.JwtLoginService)
org.jose4j.jwt.consumer.InvalidJwtException: JWT processing failed. Additional details: [[17] Unable to process JOSE object (cause: org.jose4j.lang.JoseException: Invalid JOSE Compact Serialization. Expecting either 3 or 5 parts for JWS or JWE respectively but was 1.): clienta1]
	at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:413)
	at org.jose4j.jwt.consumer.JwtConsumer.processToClaims(JwtConsumer.java:171)
	at io.confluent.common.security.jetty.JwtLoginService.login(JwtLoginService.java:102)
	at io.confluent.common.security.jetty.JwtWithFallbackLoginService.login(JwtWithFallbackLoginService.java:53)
	at org.eclipse.jetty.security.authentication.LoginAuthenticator.login(LoginAuthenticator.java:58)
	at org.eclipse.jetty.security.authentication.BasicAuthenticator.validateRequest(BasicAuthenticator.java:92)
	at io.confluent.common.security.jetty.OAuthOrBasicAuthenticator.validateRequest(OAuthOrBasicAuthenticator.java:59)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:483)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1700)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1667)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:152)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:505)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jose4j.lang.JoseException: Invalid JOSE Compact Serialization. Expecting either 3 or 5 parts for JWS or JWE respectively but was 1.
	at org.jose4j.jwx.JsonWebStructure.fromCompactSerialization(JsonWebStructure.java:88)
	at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:327)
	... 37 more
[2019-08-17 14:01:04,405] INFO 127.0.0.1 - clienta [17/Aug/2019:04:01:04 +0000] "GET /security/1.0/authenticate HTTP/1.1" 200 645  6 (io.confluent.rest-utils.requests)

**Comment by vschandra** [comment]
Resolved it by manually granting Role permission.
