### ISSUE TITLE
Topic Creation Error

### ISSUE THREAD

**Issue by AdheipSingh** [confluentinc/examples#389]
I have decoupled the docker compose setup to run it on VM's on different regions. I am trying to create topics using this command.
```
kafka-topics  --create \
> --bootstrap-server <my_broker>:9092 \
> --topic single-region \
> --partitions 1 \
> --replica-placement single.json \
> --config min.insync.replicas=1
```

Here is my json
```
{   
    "version": 1,
    "replicas": [
        {
            "count": 2,
            "constraints": {
                "rack": "west"
            }
        }
    ]
}
```
Here is the error i am recieving

```root@cb953d88b771:/# kafka-topics  --create \
> --bootstrap-server <hostname>:9092 \
> --topic single-region \
> --partitions 1 \
> --replica-placement single.json \
> --config min.insync.replicas=1
Error while executing topic command : org.apache.kafka.common.errors.InvalidConfigurationException: Unknown topic config name: confluent.placement.constraints
[2019-12-17 12:02:34,784] ERROR java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidConfigurationException: Unknown topic config name: confluent.placement.constraints
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at kafka.admin.TopicCommand$AdminClientTopicService.createTopic(TopicCommand.scala:283)
	at kafka.admin.TopicCommand$TopicService.createTopic(TopicCommand.scala:235)
	at kafka.admin.TopicCommand$TopicService.createTopic$(TopicCommand.scala:230)
	at kafka.admin.TopicCommand$AdminClientTopicService.createTopic(TopicCommand.scala:258)
	at kafka.admin.TopicCommand$.main(TopicCommand.scala:62)
	at kafka.admin.TopicCommand.main(TopicCommand.scala)
Caused by: org.apache.kafka.common.errors.InvalidConfigurationException: Unknown topic config name: confluent.placement.constraints
 (kafka.admin.TopicCommand$)
```
Here is the log from kafka endpoint

```
[2019-12-17 12:09:27,788] INFO [Admin Manager on Broker 1]: Error processing create topic request CreatableTopic(name='single-region', numPartitions=1, replicationFactor=-1, assignments=[], configs=[CreateableTopicConfig(name='confluent.placement.constraints', value='{"version":1,"replicas":[{"count":1,"constraints":{"rack":"west"}}],"observers":[]}'), CreateableTopicConfig(name='min.insync.replicas', value='1')]) (kafka.server.AdminManager)
```
Kafka version : **5.4.0-ccs-beta1
I** have used the following versions to install confluent-kafka
```
$ wget -qO - https://packages.confluent.io/deb/5.3/archive.key | sudo apt-key add -
$ sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/beta201908/deb/5.4 stable main"
$ sudo apt-get update && sudo apt-get install confluent-platform-2.12
```
Using this repo versions, ----replica-placement command is not available. 
I have used this doc for reference
```https://docs.confluent.io/current/release-notes/5-4-preview.html```

**Comment by ybyzek** [comment]
@AdheipSingh per the output above, looks like the incorrect version is being used.  Specifically, this feature is built into `confluent-server`, not `ccs`.

Directions to follow: https://docs.confluent.io/current/release-notes/5-4-preview.html#install-cs

> To use Schema Validation or Built-in Multi-Region Replication, install the confluent-server package, rather than confluent-kafka

**Comment by AdheipSingh** [comment]
@ybyzek Thanks for the reply. I am able to run the command now. Just an info the docs states 5.3 to get the key as stated below: 
```
$ wget -qO - https://packages.confluent.io/deb/5.3/archive.key | sudo apt-key add -
```
It should be updated to ```https://packages.confluent.io/beta201908/deb/5.4/archive.key ```
:)

**Comment by ybyzek** [comment]
Thank you!  I filed a docs jira to address this
